---
- name: Update all installed packages using YUM module
  yum:
    name: '*'
    state: latest
    update_cache: true
    update_only: true
  register: yum_update_status

- name: Remove packates not needed anymore
  yum:
    autoremove: true

- name: Reboot when packages were updated
  reboot:
  when: yum_update_status.changed
